// Alerts
export const ALERT_SET = 'ALERT_SET';
export const ALERT_REMOVE = 'ALERT_REMOVE';
export const ALERT_RESET = 'ALERT_RESET';

// Register & Log In
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Recipes page
export const RECIPE_LOAD_PAGE_REQUEST = 'RECIPE_LOAD_PAGE_REQUEST';
export const RECIPE_LOAD_PAGE_SUCCESS = 'RECIPE_LOAD_PAGE_SUCCESS';
export const RECIPE_LOAD_PAGE_FAIL = 'RECIPE_LOAD_PAGE_FAIL';
export const RECIPE_LOAD_PAGE_RESET = 'RECIPE_LOAD_PAGE_RESET';

// Create new recipe
export const RECIPE_CREATE_RECIPE_SUCCESS = 'RECIPE_CREATE_RECIPE_SUCCESS';
export const RECIPE_CREATE_RECIPE_FAIL = 'RECIPE_CREATE_RECIPE_FAIL';
export const RECIPE_CREATE_RECIPE_RESET = 'RECIPE_CREATE_RECIPE_RESET';

// Load single recipe page
export const RECIPE_LOAD_SINGLE_SUCCESS = 'RECIPE_LOAD_SINGLE_SUCCESS';
export const RECIPE_LOAD_SINGLE_FAIL = 'RECIPE_LOAD_SINGLE_FAIL';
export const RECIPE_LOAD_SINGLE_RESET = 'RECIPE_LOAD_SINGLE_RESET';

// Add comment
export const RECIPE_ADD_COMMENT_SUCCESS = 'RECIPE_ADD_COMMENT_SUCCESS';
export const RECIPE_ADD_COMMENT_FAIL = 'RECIPE_ADD_COMMENT_FAIL';

// Update Recipe's rating
export const RECIPE_UPDATE_RATING_SUCCESS = 'RECIPE_UPDATE_RATING_SUCCESS';
export const RECIPE_UPDATE_RATING_FAIL = 'RECIPE_UPDATE_RATING_FAIL';
